version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
    restart: always
  eureka-server:
    image: zvozdin/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
    networks:
      - spring
    depends_on:
      - zipkin
    restart: always
  apigw:
    image: zvozdin/api-gateway:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      SPRING_ZIPKIN_BASEURL: ${SPRING_ZIPKIN_BASEURL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      spring.cloud.gateway.routes.customer.uri: CUSTOMER
#      spring.cloud.gateway.routes.customer.uri: customer
    networks:
      - spring
    depends_on:
      - eureka-server
      - zipkin
  customer:
    image: zvozdin/customer:latest
    container_name: customer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_ZIPKIN_BASEURL: ${SPRING_ZIPKIN_BASEURL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      RABBIT_URI: ${RABBIT_URI}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server
  fraud:
    image: zvozdin/fraud:latest
    container_name: fraud
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fraud
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_ZIPKIN_BASEURL: ${SPRING_ZIPKIN_BASEURL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      RABBIT_URI: ${RABBIT_URI}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server
  notification:
    image: zvozdin/notification:latest
    container_name: notification
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notification
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_ZIPKIN_BASEURL: ${SPRING_ZIPKIN_BASEURL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      RABBIT_URI: ${RABBIT_URI}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - eureka-server
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
